openapi: 3.0.0

info:
  title: Announcements
  description: A microservice responsible for creating/retrieving announcements
  version: 0.0.1

servers:
  - url: https://yb9pqd6u0f.execute-api.eu-central-1.amazonaws.com
    description: A public API for retriving announcements
  - url: https://8htui023p8.execute-api.eu-central-1.amazonaws.com
    description: A private API for creating announcements

paths:
  /Prod/announcements/:
    get:
      summary: Returns a list of announcements.
      description: Available through the public API server. Supports pagination
      
      servers:
        - url: https://yb9pqd6u0f.execute-api.eu-central-1.amazonaws.com

      parameters:
        - in: query
          name: limit
          description: Maximum number of announcements
          schema:
            type: integer
            minimum: 0
            maximum: 100
            default: 10
        - in: query
          name: last_key
          description: Announcement id from which the scan should start
          schema:
            type: string
            default: null

  
      responses:
        '200':
          description: A JSON object with a list of items and pagination metadata
          content:
            application/json:
              schema:
                type: object
                properties:
                  Count:
                    type: integer
                  Items:
                    type: array
                    items:
                      $ref: '#components/schemas/Announcement'
                  ScannedCount:
                    type: integer
        '400':
          description: Errors about invalid parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
    post:
      summary: Creates a new announcement
      description: Available through the private API server. 
      security:
        - bearerAuth: []
      
      servers:
        - url: https://8htui023p8.execute-api.eu-central-1.amazonaws.com

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                title:
                  type: string
      
      responses:
        '201':
          description: Success message when an item has been created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '401':
          description: Access token is missing or invalid
        '400':
          description: Errors about invalid parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object

  /Prod/get-user-token/:
    get:
      summary: Retrieve a user access token. Make sure you've god a user create through the AWS cognito console first.
      servers:
        - url: https://yb9pqd6u0f.execute-api.eu-central-1.amazonaws.com
      
      parameters:
        - in: query
          name: email
          schema:
            type: string
            format: email
            default: vlad.mashkin@yahoo.com
        - in: query
          name: password
          schema:
            type: string
            format: email
            default: '222222ss'

      responses:
        '200':
          description: Retrieve a user access token
          content:
            application/json:
              schema:
                type: object
                properties:
                  IdToken:
                    type: string

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
 
  schemas:
    Announcement:
      type: object
      properties:
        date:
          type: string
        description:
          type: string
        id:
          type: string
        title:
          type: string
      required:
        - title
        - description
